@host=https://localhost:7298

GET {{host}}/dinners
Content-Type: application/json
Authorization: : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJnaXZlbl9uYW1lIjoiWXVyaXkiLCJmYW1pbHlfbmFtZSI6IlNvZ29rb24iLCJqdGkiOiIxMzZkOGFiZC0zMTAwLTRhZmQtOWI3ZC03OThlM2IwZTgzNjgiLCJleHAiOjE2Njk0MjI3MjksImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.CvQhYn5iF5SYebV2n-tMRpG_m2tA4uZF3fRYKhc6Qd8